CREATE TABLE abilities
   (
      name VARCHAR(20) NOT NULL PRIMARY KEY,
      boost_stat VARCHAR(20) NOT NULL,
      boost_amount SMALLINT NOT NULL
   );
   
CREATE TABLE moves
   (
      name VARCHAR(20) NOT NULL PRIMARY KEY,
      type1 VARCHAR(12),
      power SMALLINT,
      accuracy SMALLINT,
      pp SMALLINT NOT NULL,
      effect SMALLINT,
      description VARCHAR(160) NOT NULL
   );
   
CREATE TABLE pokemon
   (
      id SMALLINT NOT NULL PRIMARY KEY,
      name VARCHAR(12) NOT NULL,
      type1 VARCHAR(12) NOT NULL,
      type2 VARCHAR(12),
      category VARCHAR(25) NOT NULL,
      capture_rate SMALLINT NOT NULL,
      hp SMALLINT NOT NULL,
      atk SMALLINT NOT NULL,
      ascii_art VARCHAR(4500) NOT NULL
   );
CREATE INDEX pkmn_name_idx ON pokemon(name);
CREATE INDEX pkmn_type1_idx ON pokemon(type1);
CREATE INDEX pkmn_type2_idx ON pokemon(type2);

CREATE TABLE trainer
   (
      id INTEGER
         GENERATED BY DEFAULT AS IDENTITY
	 NOT NULL PRIMARY KEY,
      name VARCHAR(8) NOT NULL,
      gender VARCHAR(1)
   );

CREATE TABLE ownedpokemon
   (
      id INTEGER
         GENERATED BY DEFAULT AS IDENTITY
         NOT NULL PRIMARY KEY,
      trainer_id INTEGER NOT NULL,
      FOREIGN KEY (trainer_id) REFERENCES trainer(id)
         ON DELETE CASCADE,
      pkmn_id SMALLINT NOT NULL,
      FOREIGN KEY (pkmn_id) REFERENCES pokemon(id),
      nickname VARCHAR(12),
      gender VARCHAR(1),
      in_team BOOLEAN NOT NULL,
      m1 VARCHAR(20), m2 VARCHAR(20), m3 VARCHAR(20), m4 VARCHAR(20),
      FOREIGN KEY (m1) REFERENCES moves(name),
      FOREIGN KEY (m2) REFERENCES moves(name),
      FOREIGN KEY (m3) REFERENCES moves(name),
      FOREIGN KEY (m4) REFERENCES moves(name),
      ability VARCHAR(12) NOT NULL,
      FOREIGN KEY (ability) REFERENCES abilities(name)
   );
CREATE INDEX trainer_pkmns ON ownedpokemon(trainer_id, in_team);

CREATE TABLE learnablemove
   (
      move_name VARCHAR(20) NOT NULL,
      FOREIGN KEY (move_name) REFERENCES moves(name),
      can_be_learned_by_pkmn_id SMALLINT NOT NULL,
      FOREIGN KEY  (can_be_learned_by_pkmn_id) REFERENCES pokemon(id)
   );
CREATE INDEX pkmn_moves ON learnablemove(can_be_learned_by_pkmn_id);

CREATE TABLE learnableability
   (
      ability_name VARCHAR(20) NOT NULL,
      FOREIGN KEY (ability_name) REFERENCES abilities(name),
      can_be_learned_by_pkmn_id SMALLINT NOT NULL,
      FOREIGN KEY (can_be_learned_by_pkmn_id) REFERENCES pokemon(id)
   );
CREATE INDEX pkmn_abilities ON learnableability(can_be_learned_by_pkmn_id);


